In [1]:
import pandas as pd

In [2]:
data = pd.read_pickle("../data/processed/memory_optimized_data.pkl")

In [134]:
data.head()

,event_id,game_session,timestamp,event_data,installation_id,event_count,event_code,game_time,title,type,world
0,27253bdc,45bb1e1b6b50c07b,2019-09-06 17:53:46.937000+00:00,"{""event_code"": 2000, ""event_count"": 1}",0001e90f,1,2000,0,Welcome to Lost Lagoon!,Clip,NONE
1,27253bdc,17eeb7f223665f53,2019-09-06 17:54:17.519000+00:00,"{""event_code"": 2000, ""event_count"": 1}",0001e90f,1,2000,0,Magma Peak - Level 1,Clip,MAGMAPEAK
2,77261ab5,0848ef14a8dc6892,2019-09-06 17:54:56.302000+00:00,"{""version"":""1.0"",""event_count"":1,""game_time"":0...",0001e90f,1,2000,0,Sandcastle Builder (Activity),Activity,MAGMAPEAK
3,b2dba42b,0848ef14a8dc6892,2019-09-06 17:54:56.387000+00:00,"{""description"":""Let's build a sandcastle! Firs...",0001e90f,2,3010,53,Sandcastle Builder (Activity),Activity,MAGMAPEAK
4,1bb5fbdb,0848ef14a8dc6892,2019-09-06 17:55:03.253000+00:00,"{""description"":""Let's build a sandcastle! Firs...",0001e90f,3,3110,6972,Sandcastle Builder (Activity),Activity,MAGMAPEAK

['0001e90f', '000447c4', '0006a69f', '0006c192', '0009a5a9']

In [132]:
#List all titles
# pd.DataFrame(data.title.unique())

In [171]:
def create_feature_dataframe():
    columns=['installation_id']+list((data.title.unique()))
    prodf = pd.DataFrame(columns = columns)
    return prodf

In [172]:
def create_individual_feature_dataframe(installation_id_temp):
    extract2=data[data['installation_id']==installation_id_temp]
    temp=pd.DataFrame(extract2.title.unique())
    temp=temp.set_index(temp[0])
    temp[0]=1
    temp=temp.T
    temp['installation_id']=installation_id_temp
    return temp

In [180]:
i=0
prodf = create_feature_dataframe()
installation_id_temp_array=list(data.installation_id.unique())
for installation_id_temp in installation_id_temp_array:
    if i%2==0:
        print(i)
    i+=1
    returned_features=create_individual_feature_dataframe(installation_id_temp)
    prodf=prodf.append(returned_features)
prodf

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100

KeyboardInterrupt:

In [179]:
prodf

,12 Monkeys,Air Show,All Star Sorting,Balancing Act,Bird Measurer (Assessment),Bottle Filler (Activity),Bubble Bath,Bug Measurer (Activity),Cart Balancer (Assessment),Cauldron Filler (Assessment),...,Sandcastle Builder (Activity),Scrub-A-Dub,Slop Problem,Treasure Map,Tree Top City - Level 1,Tree Top City - Level 2,Tree Top City - Level 3,Watering Hole (Activity),Welcome to Lost Lagoon!,installation_id
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,1,NaN,NaN,1,NaN,NaN,NaN,1,0001e90f
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,000447c4
0,1,1,1,NaN,1,1,1,1,NaN,NaN,...,1,1,1,1,1,1,1,1,1,0006a69f
0,1,NaN,NaN,1,1,1,1,1,NaN,1,...,1,1,NaN,1,1,1,1,1,1,0006c192
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,1,NaN,NaN,NaN,NaN,1,1,0009a5a9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,1,1,NaN,1,0011edc8
0,NaN,NaN,NaN,1,1,1,NaN,1,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,00129856
0,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,1,NaN,1,1,NaN,NaN,1,0016b7cc
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,1,NaN,NaN,NaN,NaN,1,1,00195df7
0,NaN,NaN,NaN,1,1,NaN,NaN,NaN,1,NaN,...,NaN,1,NaN,1,1,1,1,NaN,1,001d0ed0
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,1,002114ae
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,00219589
0,1,1,1,1,1,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,1,1,1,1,NaN,1,00225f67
0,1,1,1,NaN,NaN,1,1,1,NaN,NaN,...,1,1,1,1,1,1,1,1,1,00279ac5
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,002c8bae
0,1,1,1,NaN,1,1,1,1,1,1,...,1,1,NaN,1,1,1,1,1,1,002db7e3
0,1,1,1,1,1,1,1,1,1,1,...,1,1,NaN,1,1,1,1,1,1,003372b0
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0034471d